name: Build phar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install box.phar
      run: composer box-install

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Compile phar
      run: composer box-compile
      
    - name: Generate drush.version
      run: sha1sum drush.phar > drush.version

    - uses: actions/upload-artifact@v2
      with:
        name: drush
        path: drush.phar
        
    - uses: actions/upload-artifact@v2
      with:
        name: drush
        path: drush.version
